name: build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.18.0'

      - name: Install Ziti CI
        uses: netfoundry/ziti-ci@v1

      - name: Build and Test
        run: |
          go install gotest.tools/gotestsum@latest
          $(go env GOPATH)/bin/gotestsum --jsonfile test-output.json --junitfile test-output-junit.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'test-output-junit.xml'
          annotate_only: true

      - name: Release
        env:
          gh_ci_key: ${{ secrets.GH_CI_KEY }}
          ziti_ci_gpg_key: ${{ secrets.ZITI_CI_GPG_KEY }}
          ziti_ci_gpg_key_id: ${{ secrets.ZITI_CI_GPG_KEY_ID }}
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release-')
        run: |
          $(go env GOPATH)/bin/ziti-ci configure-git
          $(go env GOPATH)/bin/ziti-ci tag -v -f version
          $(go env GOPATH)/bin/ziti-ci trigger-github-build openziti/storage update-dependency --token ${{ secrets.ZITI_CI_GH_TOKEN }}
          $(go env GOPATH)/bin/ziti-ci trigger-github-build openziti/transport update-dependency --token ${{ secrets.ZITI_CI_GH_TOKEN }}
          $(go env GOPATH)/bin/ziti-ci trigger-github-build openziti/sdk-golang update-dependency --token ${{ secrets.ZITI_CI_GH_TOKEN }}
